site_name: SOP 文件
site_url: https://yayihuang-bit.github.io/sop-docs/
theme:
  name: material
  language: zh-TW
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
  custom_dir: overrides

nav:
  - 首頁: index.md
  - 遊戲上線工作:
    - 首頁: 遊戲上線工作_索引.md
    - 遊戲上線設定: 遊戲上線SOP.md
    - 遊戲調整流程: 遊戲調整流程.md
  - 營運活動教學:
    - 首頁: 營運_索引.md
    - 換皮資訊: 換皮資訊_索引.md
    - 抽獎:
      - 首頁: 抽獎_索引.md
      - 直播流程: 直播流程.md
      - 抽獎流程: 抽獎流程.md
  - 競品指南: 競品指南_索引.md

plugins:
  - search:
      lang: zh-TW

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

