site_name: SOP 文件
site_url: https://yayihuang-bit.github.io/sop-docs/
theme:
  name: material
  language: zh-TW
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
  custom_dir: overrides

plugins:
  - search:
      lang: zh-TW

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

